"""Unified Modular Daily Job Application Engine."""

from .config import (
    BASE_DIR,
    CONFIG_DIR,
    CONFIGS_DIR,
    COVER_LETTERS_DIR,
    JOB_DESCRIPTIONS_DIR,
    JOBS_DIR,
    MASTER_INDEX,
    RESUMES_DIR,
    ROLES_DIR,
    ROLES_HTML_DIR,
    ROLES_PDF_DIR,
    load_profile,
    set_active_profile,
    sync_stylesheets,
)
from .cover_letter import (
    DIN_5008_TEMPLATE,
    build_cover_letter_from_config,
    format_german_date,
    get_ngrams,
    validate_cover_letter_file,
)
from .pdf import export_pdfs, find_browser, html_to_pdf
from .resume import (
    DOMStructureParser,
    build_all_roles,
    build_resume_from_config,
    build_role,
    generate_resume_html,
    get_resume_config,
    validate_resume_file,
)
from .search_links import build_daily_search_links, init_config

__all__ = [
    "BASE_DIR",
    "CONFIG_DIR",
    "CONFIGS_DIR",
    "COVER_LETTERS_DIR",
    "JOB_DESCRIPTIONS_DIR",
    "JOBS_DIR",
    "MASTER_INDEX",
    "RESUMES_DIR",
    "ROLES_DIR",
    "ROLES_HTML_DIR",
    "ROLES_PDF_DIR",
    "load_profile",
    "set_active_profile",
    "sync_stylesheets",
    "DIN_5008_TEMPLATE",
    "build_cover_letter_from_config",
    "format_german_date",
    "get_ngrams",
    "validate_cover_letter_file",
    "export_pdfs",
    "find_browser",
    "html_to_pdf",
    "DOMStructureParser",
    "build_all_roles",
    "build_resume_from_config",
    "build_role",
    "generate_resume_html",
    "get_resume_config",
    "validate_resume_file",
    "build_daily_search_links",
    "init_config",
]
